### ISSUE TITLE
UX- Overall Grade

### ISSUE THREAD

**Issue by chonnens** [drexnexlo/web-iv-portfolio-site#12]
Overall Grade: Proficient

Overall things make sense and are accessible. One of the main irritants as a user is that the logo doesn't link to home. Most other issues are small technical or spacing things.

**Comment by e-m-durham** [comment]
Good points brought up by your peers. However, I'd probably be more likely to assess this currently more around the "Satisfactory" range because of the nav, the email link that'd be a pain to access on mobile. Not enough to make an overall frustrating experience, but could cause moments of frustration.
